### PR TITLE
fix: Do not create default zone_awareness_config if it not set

### PR DESCRIPTION
**Pull request by strangeman**
### Current behavior

If I don't define the `cluster_config.zone_awareness_config` (or define it as an empty map, e.g `zone_awareness_config={}`), the module creates the following `zone_awareness_config` anyway:

```
      ~ cluster_config {
            # (8 unchanged attributes hidden)

          + zone_awareness_config {
              + availability_zone_count = 2
            }

            # (1 unchanged block hidden)
        }
```

### Expected behavior

That block should be omitted if I don't define the `cluster_config.zone_awareness_config`.

### Why it's happening

The current code creates the `zone_awareness_config` block even if `cluster_config.value.zone_awareness_config` is empty or omitted. This behavior was reflected (but not so quietly) in provider documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#zone_awareness_config

> [availability_zone_count](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain#availability_zone_count) - (Optional) Number of Availability Zones for the domain to use with zone_awareness_enabled. Defaults to 2. Valid values: 2 or 3.

So, if we pass an empty map for the `zone_awareness_config` in the `aws_elasticsearch_domain`, the provider sets `availability_zone_count = 2` by default. 

In my opinion, this is unclear behavior of the provider, but we can mitigate it in the module if we'll pass a `null` instead of an empty map in case of an undefined `cluster_config.value.zone_awareness_config`.

## Motivation and Context

In the case of disabled zone awareness (`zone_awareness_enabled = false`) undefined  `cluster_config.value.zone_awareness_config` causes non-idempotent runs of Terraform, because the module tries to create a `zone_awareness_config` block each run and didn't succeed, because zone awareness is disabled. That PR will fix it.

## Breaking Changes

No, this is a minor change.

### CODE REVIEW

**Comment by bryantbiggs** [comment]
ignoring the deviation from provider/API defaults, why would you want this?

**Comment by strangeman** [comment]
In stage environments, we use clusters without zone awareness. With the current module, each Terraform run generates junk changes, like
```
  # module.opensearch.aws_opensearch_domain.this[0] will be updated in-place
  ~ resource "aws_opensearch_domain" "this" {
        id                 = "arn:aws:es:us-east-2:XXXXXX:domain/YYYYYY"
        tags               = {
            "Environment"           = "stage"
            "Terraform"             = "true"
            "terraform-aws-modules" = "opensearch"
        }
        # (10 unchanged attributes hidden)

      ~ cluster_config {
            # (8 unchanged attributes hidden)

          + zone_awareness_config {
              + availability_zone_count = 2
            }

            # (1 unchanged block hidden)
        }

        # (11 unchanged blocks hidden)
    }
```
even if nothing really changed. It's confusing and breaks the idempotence of the current Terraform code.

**Comment by bryantbiggs** [comment]
I don't follow - this sounds like Terraform is syncing with changes made by the AWS API

**Comment by strangeman** [comment]
No, this is probably unclear behavior (or even a bug) in the AWS provider, causing the difference between the Terraform state and the real state in AWS. If I use 'plain' `aws_opensearch_domain` with the following configuration:
```
 cluster_config {
    zone_awareness_enabled = false
    zone_awareness_config = {}
  }
```
then I'll get the same problem. 

The provider will try to create a resource with `availability_zone_count = 2` (because it is the default value), will complete it successfully, and will write `availability_zone_count = 2` to the TF state. But because zone awareness is disabled (by `zone_awareness_enabled = false`) these changes won't reflect in the real AWS state.

So, at the next run, TF will refresh the state by AWS API and find that difference, which causes another try to apply it.

**Comment by bryantbiggs** [comment]
> No, this is probably unclear behavior (or even a bug) in the AWS provider, causing the difference between the Terraform state and the real state in AWS.

Then I would suggest opening an issue on the provider to have the issue resolved there

**Comment by strangeman** [comment]
Okay, I just hoped it is possible to add a fix here too because this is much faster. :)

**Comment by bryantbiggs** [comment]
if it is a computed default value, no. we would just be fighting with the value computed and set by the provider/API and that would raise more issues than benefits (if any)

**Comment by strangeman** [comment]
BTW this bug has existed for at least from 2020 year and nobody seems interested in it :(

https://github.com/hashicorp/terraform-provider-aws/issues/15730

**Comment by strangeman** [comment]
That parent issue was closed as `not planned`, it seems they think it is planned behavior if `zone_awareness_enabled` is `false` and `zone_awareness_config` is `{}`. So, the way to deal with it in resource - is just to omit the zone_awareness_config block. But I can't do it in the module, because the module code always puts the `{}` if zone_awareness_config is undefined. I think this is wrong and it is easy to fix and shouldn't break anything.

**Comment by bryantbiggs** [comment]
do you have a minimal reproduction?

**Comment by strangeman** [comment]
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.42.0"
    }
  }
  required_version = "1.7.5"
}

provider "aws" {}

module "opensearch" {
  source      = "terraform-aws-modules/opensearch/aws"
  version     = "1.1.0"
  domain_name = "awareness-bug"
  cluster_config = {
    instance_count           = 1
    dedicated_master_enabled = false
    instance_type            = "t3.small.search"
    zone_awareness_enabled   = false
  }
  auto_tune_options = {
    desired_state       = "DISABLED"
    rollback_on_disable = "NO_ROLLBACK"
  }
  ebs_options = {
    ebs_enabled = true
    iops        = 3000
    throughput  = 125
    volume_type = "gp3"
    volume_size = 10
  }
  engine_version         = "OpenSearch_2.11"
  log_publishing_options = []
}
```

After initial creation, each time when you run `terraform apply` it will show the following changes:
```
  # module.opensearch.aws_opensearch_domain.this[0] will be updated in-place
  ~ resource "aws_opensearch_domain" "this" {
        id                 = "arn:aws:es:us-east-1:XXXXXX:domain/awareness-bug"
        tags               = {
            "terraform-aws-modules" = "opensearch"
        }
        # (9 unchanged attributes hidden)

      ~ cluster_config {
            # (8 unchanged attributes hidden)

          + zone_awareness_config {
              + availability_zone_count = 2
            }

            # (1 unchanged block hidden)
        }

        # (10 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by antonbabenko** [comment]
This PR is included in version 1.1.2 :tada:

**Pull request merged**
