### PR TITLE
docs: Clarify Complete Example and Inputs

### PR DESCRIPTION
**Pull request by younsl**
## Description

No code changes, only update docs and `complete` examples.

## Motivation and Context

- Clarify complete example
- Update `engine_version` and `off_peak_window_options` input in docs

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

```console
$ pre-commit run -a
Terraform validate.......................................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
```

### CODE REVIEW

**Comment by bryantbiggs** [comment]
why?

**Comment by younsl** [comment]
@bryantbiggs To make it easier for Terraform users to work with the module.

**Comment by bryantbiggs** [comment]
How so?

**Comment by younsl** [comment]
> How so?

- Added example values to the complete example and provided additional context in the input documentation to enhance user understanding.

Based on my user experience (using this module `v1.4.0`), the input descriptions were relatively lacking compared to the OpenSearch Terraform module maintained by CloudPosse, and the absence of many example values made it inconvenient.

Additionally, the fact that `snapshot_options` is not supported by this module `v1.4.0` falls under a similar context.

**Comment by bryantbiggs** [comment]
thank you but unfortunately, this is what the documented variables are for. examples just demonstrate various configurations but they are not exhaustive. The documented inputs are there to show users what values the module accepts as inputs, not the examples https://github.com/terraform-aws-modules/terraform-aws-opensearch/blob/master/README.md#inputs

**Pull request closed without merging**
